version: "3.7"

services:
  fittrix_db:
    image: mysql:5.7
    container_name: fittrix_db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fittrix_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: fittrix_db
      MYSQL_PASSWORD: adminadmin
      MYSQL_ROOT_PASSWORD: adminadmin
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --sql_mode=
    volumes:
      - ./docker-mysql/:/docker-entrypoint-initdb.d
